/**
 * @file  PassDetails.h
 * @brief Private pass declarations generated by TableGen.
 *
 * This header is *internal* to the transform library.  It defines the
 * `gen-*` pass base classes that concrete implementations inherit from.
 * Down-stream code should never include this file; use Passes.h instead.
 */

#ifndef AIS_TRANSFORMS_PASSDETAILS_H
#define AIS_TRANSFORMS_PASSDETAILS_H

#include "ais/Dialect/AIS/Transforms/Passes.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"

namespace mlir::ais {

#define GEN_PASS_DEF_NORMALIZEAGENTGRAPH
#define GEN_PASS_DEF_CAPABILITYSCHEDULING
#define GEN_PASS_DEF_FUSEREASONING
#define GEN_PASS_DEF_AISTOASYNCPASS
#include "ais/Dialect/AIS/Transforms/Passes.h.inc"

}  // namespace mlir::ais

#endif  // AIS_TRANSFORMS_PASSDETAILS_H
